# Tayler Stegman
## Week13 11/14/2023
### Python - Pandas DataFrame Processing

In [1]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [4]:
#Drop entries
df = DataFrame(np.arange(16).reshape(4,4),
               index = ['Ohio', 'Colorado', 'Utah', 'New York'], 
               columns=['one','two','three','four']
              )
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [5]:
df1 = df.copy()
df1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [6]:
df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
df.index

Index(['Ohio', 'Colorado', 'Utah', 'New York'], dtype='object')

In [8]:
df.columns

Index(['one', 'two', 'three', 'four'], dtype='object')

In [9]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [12]:
#does not permanently drop from data frame. only for this line
df.drop(['Colorado'])

one  two  three  four
Ohio        0    1      2     3
Utah        8    9     10    11
New York   12   13     14    15

In [13]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [14]:
df.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [15]:
df

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [17]:
df.drop(['one','four'],axis=1)

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [18]:
df.drop(['one','four'],axis='columns')

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [19]:
#if only dropping 1 you don't need a list
df.drop('two',axis='columns')

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [25]:
#how to make a drop permanent USE INPLACE
df.drop(['one','four'],inplace=True,axis='columns')

KeyError: "['one' 'four'] not found in axis"

In [26]:
df

two  three
Ohio        1      2
Colorado    5      6
Utah        9     10
New York   13     14

In [27]:
#copy 
df1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [30]:
df1['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [31]:
df1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [32]:
df1.loc[['Colorado','Utah']]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11

In [33]:
df1[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [36]:
df1.iloc[[0,1]]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [37]:
df1.iloc[3]

one      12
two      13
three    14
four     15
Name: New York, dtype: int32

In [38]:
df1[df1['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [39]:
df1 > 5

one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

In [40]:
df1.loc['Colorado']

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [42]:
df1.loc['Colorado',['one', 'four']]

one     4
four    7
Name: Colorado, dtype: int32

In [43]:
df1['one']

Ohio         0
Colorado     4
Utah         8
New York    12
Name: one, dtype: int32

In [44]:
df1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [45]:
df1.iloc[1,[0,3]]

one     4
four    7
Name: Colorado, dtype: int32

In [46]:
df1.iloc[[0,1], [0,3]]

one  four
Ohio        0     3
Colorado    4     7

In [47]:
df1.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    4    5
Utah        11    8    9

In [48]:
df1

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [23]:
#Arithmetic and alignment of data
df1 = DataFrame(np.arange(9).reshape(3,3),
                columns=list('bcd'),
               index=['Ohio', 'Texas', 'Colorado'])

df2 = DataFrame(np.arange(12).reshape(4,3),
                columns=list('bde'),
               index=['Utah', 'Texas', 'Colorado', 'Oregon'])

In [24]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [25]:
df2

b   d   e
Utah      0   1   2
Texas     3   4   5
Colorado  6   7   8
Oregon    9  10  11

In [26]:
list('bde')

['b', 'd', 'e']

In [27]:
df2.values

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
df1.values

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [29]:
df1 + df2

b   c     d   e
Colorado  12.0 NaN  15.0 NaN
Ohio       NaN NaN   NaN NaN
Oregon     NaN NaN   NaN NaN
Texas      6.0 NaN   9.0 NaN
Utah       NaN NaN   NaN NaN

In [30]:
df1.add(df2)

b   c     d   e
Colorado  12.0 NaN  15.0 NaN
Ohio       NaN NaN   NaN NaN
Oregon     NaN NaN   NaN NaN
Texas      6.0 NaN   9.0 NaN
Utah       NaN NaN   NaN NaN

In [31]:
df1.add(df2,fill_value=0) #Fill the nan + Number with 0 + number

b    c     d     e
Colorado  12.0  7.0  15.0   8.0
Ohio       0.0  1.0   2.0   NaN
Oregon     9.0  NaN  10.0  11.0
Texas      6.0  4.0   9.0   5.0
Utah       0.0  NaN   1.0   2.0

In [32]:
df1

b  c  d
Ohio      0  1  2
Texas     3  4  5
Colorado  6  7  8

In [33]:
#adds column e which is the result of b + d
df1['e'] = df1['b'] + df1['d']
df1

b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [34]:
#Operation between DataFrame and Series
df2

b   d   e
Utah      0   1   2
Texas     3   4   5
Colorado  6   7   8
Oregon    9  10  11

In [35]:
s = df2.iloc[0]
s

b    0
d    1
e    2
Name: Utah, dtype: int32

In [36]:
df2

b   d   e
Utah      0   1   2
Texas     3   4   5
Colorado  6   7   8
Oregon    9  10  11

In [37]:
df1

b  c  d   e
Ohio      0  1  2   2
Texas     3  4  5   8
Colorado  6  7  8  14

In [38]:
df2 - s

b  d  e
Utah      0  0  0
Texas     3  3  3
Colorado  6  6  6
Oregon    9  9  9

In [44]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
#sort and rank
df3 = DataFrame(np.arange(8).reshape(2,4) * 10,
              columns=list('dabc'),
              index=['three','one'])
df3

d   a   b   c
three   0  10  20  30
one    40  50  60  70

In [45]:
df3.sort_index()

d   a   b   c
one    40  50  60  70
three   0  10  20  30

In [47]:
#sort columns using axis 1
df3.sort_index(axis=1)

a   b   c   d
three  10  20  30   0
one    50  60  70  40

In [48]:
df3.sort_index(axis=1,ascending=False)

d   c   b   a
three   0  30  20  10
one    40  70  60  50

In [49]:
df4 = DataFrame({'b': [4,7,-3,2], 'a': [0,-1,3,2]})
df4

b  a
0  4  0
1  7 -1
2 -3  3
3  2  2

In [50]:
#Sort data by columns 'b'
df4.sort_values(by='b')

b  a
2 -3  3
3  2  2
0  4  0
1  7 -1

In [51]:
df4.sort_values(by=['b','a'])

b  a
2 -3  3
3  2  2
0  4  0
1  7 -1

In [52]:
#ranking data'
df5 = DataFrame({'b':[14,17,-13,12],'a': [10,11,15,11]})
df5

b   a
0  14  10
1  17  11
2 -13  15
3  12  11

In [54]:
#rank of the value in the column?
df5.rank()

b    a
0  3.0  1.0
1  4.0  2.5
2  1.0  4.0
3  2.0  2.5

In [55]:
df5.rank().astype(int)

b  a
0  3  1
1  4  2
2  1  4
3  2  2

In [56]:
#Summarizing Data - Descriptive Statistics
df = DataFrame([[1.4, np.nan], [7.1,-4.5], [np.nan,np.nan], [0.75,-1.3]],
                index=list('abcd'),
                columns=['one','two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [57]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [58]:
df.sum(axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [59]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [61]:
df.mean()

one    3.083333
two   -2.900000
dtype: float64

In [62]:
df.mean(axis='columns')

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

In [63]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [64]:
df.mean(axis=1, skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [66]:
df.min()

one    0.75
two   -4.50
dtype: float64

In [67]:
df.max()

one    7.1
two   -1.3
dtype: float64

In [68]:
df.min(axis=1)

a    1.4
b   -4.5
c    NaN
d   -1.3
dtype: float64

In [69]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [73]:
#Returns index of first occurance of maximum over requested axis
df.idxmax()

one    b
two    d
dtype: object

In [75]:
df.idxmax(axis=1)

a    one
b    one
c    NaN
d    one
dtype: object

In [78]:
#the mean ignores NaN values in the count of calculation
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [86]:
#mising data
df = DataFrame([ [1,2,3,4] , [np.nan,5,6], [7,np.nan, 9], [np.nan, np.nan, np.nan]])
df

0    1    2    3
0  1.0  2.0  3.0  4.0
1  NaN  5.0  6.0  NaN
2  7.0  NaN  9.0  NaN
3  NaN  NaN  NaN  NaN

In [87]:
df.values

array([[ 1.,  2.,  3.,  4.],
       [nan,  5.,  6., nan],
       [ 7., nan,  9., nan],
       [nan, nan, nan, nan]])

In [88]:
#drop entire row if a single value has missing data
df.dropna()

0    1    2    3
0  1.0  2.0  3.0  4.0

In [89]:
df

0    1    2    3
0  1.0  2.0  3.0  4.0
1  NaN  5.0  6.0  NaN
2  7.0  NaN  9.0  NaN
3  NaN  NaN  NaN  NaN

In [90]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [91]:
#any means drop whole row if there is a single value
df.dropna(how='any')

0    1    2    3
0  1.0  2.0  3.0  4.0

In [94]:
#all means drop whole row only if it is completely null values, in this example row 3 is dropped
df.dropna(how='all')

0    1    2    3
0  1.0  2.0  3.0  4.0
1  NaN  5.0  6.0  NaN
2  7.0  NaN  9.0  NaN

In [103]:
#thresh means keep rows that have __ or in this example 2 or more Non-null values
df.dropna(thresh=2)

0    1    2    3
0  1.0  2.0  3.0  4.0
1  NaN  5.0  6.0  NaN
2  7.0  NaN  9.0  NaN

In [106]:
#thresh means keep rows that have __ or in this example 3 or moreNon-null values
df.dropna(thresh=3)

0    1    2    3
0  1.0  2.0  3.0  4.0

In [107]:
df.dropna(thresh=2,axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0
3  NaN  NaN  NaN

In [109]:
df_copy = df.copy()

In [110]:
df_copy

0    1    2    3
0  1.0  2.0  3.0  4.0
1  NaN  5.0  6.0  NaN
2  7.0  NaN  9.0  NaN
3  NaN  NaN  NaN  NaN

In [113]:
#inplace=true means to apply to the dataset so you don't have to say df = df...
df.dropna(thresh=2,axis=1, inplace=True)
df

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0
3  NaN  NaN  NaN

In [136]:
df_copy = df_copy.fillna(0)

In [127]:
df_copy = df_copy.fillna(df.mean(axis='columns'))
df_copy

0    1    2    3
0  1.0  2.0  3.0  4.0
1  4.0  5.0  6.0  0.0
2  7.0  3.5  9.0  0.0
3  4.0  3.5  6.0  0.0

In [131]:
#value counts
df = DataFrame({'Qu1': [10,30,40,30,40],
               'Qu2': [20,30,10,20,30],
               'Qu3': [10, 50, 20, 40,40]},
              index=list('abcde'))
df

Qu1  Qu2  Qu3
a   10   20   10
b   30   30   50
c   40   10   20
d   30   20   40
e   40   30   40

In [132]:
df['Qu1'].value_counts()

30    2
40    2
10    1
Name: Qu1, dtype: int64

In [133]:
df['Qu3'].value_counts()

40    2
20    1
10    1
50    1
Name: Qu3, dtype: int64

In [134]:
df.loc['a'].value_counts()

10    2
20    1
Name: a, dtype: int64

In [137]:
df.iloc[1].value_counts()

30    2
50    1
Name: b, dtype: int64

In [139]:
df.apply(pd.value_counts)

Qu1  Qu2  Qu3
10  1.0  1.0  1.0
20  NaN  2.0  1.0
30  2.0  2.0  NaN
40  2.0  NaN  2.0
50  NaN  NaN  1.0

In [142]:
df.apply(pd.value_counts).fillna(0).astype(int)

Qu1  Qu2  Qu3
10    1    1    1
20    0    2    1
30    2    2    0
40    2    0    2
50    0    0    1

In [143]:
rs = df.apply(pd.value_counts).fillna(0).astype(int)

In [144]:
rs

Qu1  Qu2  Qu3
10    1    1    1
20    0    2    1
30    2    2    0
40    2    0    2
50    0    0    1

In [146]:
rs.index.name='Score'
rs.columns.name='Questions'
rs

Questions  Qu1  Qu2  Qu3
Score                   
10           1    1    1
20           0    2    1
30           2    2    0
40           2    0    2
50           0    0    1