# Tayler Stegman
## Week 10 - 10/24/2023
### Python numpy into

In [1]:
'''
NumPy is a Python library.
NumPy is used for working with arrays.
NumPy is short for "Numerical Python".

50x faster than traditional Python lists
'''

import numpy as np

In [2]:
np.__version__

'1.18.5'

In [4]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([1, 2, 3, 4, 5])

In [8]:
# Dimensions in Arrays
# 0-D arrays, scalars
arr_0d = np.array(50)
print(arr_0d)

50


In [9]:
#shows number of dimensions
print(arr_0d,arr_0d.ndim)

50 0


In [13]:
#1-D array
# An array that has 0-D arrays as its elements
arr_1d = np.array([1,2,3,4,5,6])
print(arr_1d, type(arr_1d), arr_1d.ndim)

[1 2 3 4 5 6] <class 'numpy.ndarray'> 1


In [14]:
#2-D array
# An array that had 1-D array as its elements
arr_2d = np.array([[1,2,3,4,5,6],[11,22,33,44,55,66]])

In [15]:
print(arr_2d, arr_2d.ndim)  

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]] 2


In [18]:
#3-D array
# Array that has 2-D array as its elements
arr_3d = np.array([[[1,2,3], [4,5,6]], [[11,22,33], [44,55,66]]])

In [19]:
print(arr_3d, arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]] 3


In [20]:
len(arr_3d)

2

In [21]:
# Arry Indexing
print(arr_1d)
print(arr_2d)
print(arr_3d)

[1 2 3 4 5 6]
[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [22]:
arr_1d[0]

1

In [23]:
arr_1d[-1]

6

In [24]:
arr_1d.ndim

1

In [26]:
#Shows there are 6 elements in only 1 dimension
arr_1d.shape

(6,)

In [27]:
arr_2d.ndim

2

In [29]:
#Shows there are 2 rows and 6 columns
arr_2d.shape

(2, 6)

In [30]:
print(arr_2d)

[[ 1  2  3  4  5  6]
 [11 22 33 44 55 66]]


In [37]:
#numpy indexing is the same as normal lists
arr_2d[0]

array([1, 2, 3, 4, 5, 6])

In [38]:
arr_2d[1]

array([11, 22, 33, 44, 55, 66])

In [39]:
arr_2d[1][-1]

66

In [40]:
#numpy notation
arr_2d[1,-1]

66

In [41]:
arr_2d[0,0]

1

In [42]:
arr_2d[1,3]

44

In [43]:
print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 22 33]
  [44 55 66]]]


In [45]:
#Two 2-D arrays, in each 2-D array there are 2 elements. In each element there are 3 items
arr_3d.shape

(2, 2, 3)

In [46]:
arr_3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
arr_3d[1]

array([[11, 22, 33],
       [44, 55, 66]])

In [48]:
arr_3d[1,1]

array([44, 55, 66])

In [49]:
arr_3d[1,1,-1]

66

In [50]:
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [51]:
arr_3d[0,1,1]

5

In [52]:
arr_3d[1,0,-1]

33

In [53]:
#slicing numpy

'''
[start:end:step] step is considered 1, and index is excluded
[start:end:step]
[:end] start at index 0
[start:] end index will be the length of the array


'''
# Slicing 1-D Arrays
arr_1d

array([1, 2, 3, 4, 5, 6])

In [54]:
arr_1d[:3]

array([1, 2, 3])

In [55]:
arr_1d[-3:-1]

array([4, 5])

In [56]:
arr_1d[-3:]

array([4, 5, 6])

In [57]:
arr_1d[:]

array([1, 2, 3, 4, 5, 6])

In [58]:
arr_1d[::2]

array([1, 3, 5])

In [59]:
arr_1d[::-1]

array([6, 5, 4, 3, 2, 1])

In [60]:
#Slicing 2-D Arrays
arr_2d

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [61]:
arr_2d.shape

(2, 6)

In [62]:
arr_2d[0,1]

2

In [63]:
arr_2d[0,:3]

array([1, 2, 3])

In [64]:
arr_2d[1,-2:]

array([55, 66])

In [66]:
#Retrieves both list and -2 for both
arr_2d[:,-2]

array([ 5, 55])

In [67]:
#same statement
arr_2d[0:2,-2]

array([ 5, 55])

In [68]:
arr_2d[:,0:2]

array([[ 1,  2],
       [11, 22]])

In [69]:
arr_2d[1,-3:]

array([44, 55, 66])

In [70]:
#Slicing 3-D Arrays
arr_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 22, 33],
        [44, 55, 66]]])

In [71]:
arr_3d.shape

(2, 2, 3)

In [72]:
arr_3d[1,1,1]

55

In [74]:
arr_3d[1,1,-2:]

array([55, 66])

In [75]:
arr_3d[1,:,-2:]

array([[22, 33],
       [55, 66]])

In [76]:
arr_3d[0,:,0:2]

array([[1, 2],
       [4, 5]])

In [77]:
arr_3d[:,:,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[11, 22],
        [44, 55]]])

In [80]:
arr_d = np.array([  [[1,2], [4,5]], [[7,8],[10,11,3]] ])
print(arr_d)

[[list([1, 2]) list([4, 5])]
 [list([7, 8]) list([10, 11, 3])]]


In [81]:
arr_d.ndim

2

In [82]:
arr_d.shape

(2, 2)

In [83]:
arr_d[0,1]

[4, 5]

In [84]:
type(arr_d[0,1])

list